### PR TITLE
Hello pull request

### PR DESCRIPTION
**Pull request by saltowl**
R = are. It's slang.

### CODE REVIEW

**Comment by saltowl** [comment]
What about other services, @ZalkinV ? I mean _GitLab_ and **Bitbucket**

**Comment by ZalkinV** [comment]
It is your first pull request in this repository!
image

**Comment by ZalkinV** [comment]
> What about other services, @ZalkinV ? I mean _GitLab_ and **Bitbucket**

I did not have create account there, yet

**Comment by saltowl** [comment]
> > What about other services, @ZalkinV ? I mean _GitLab_ and **Bitbucket**
> 
> I did not have create account there, yet

### It's a pity!

**Pull request merged**
